version: 2.1
executors:
  ubuntu_executor:
    docker:
      - image: cimg/azure:2023.03.1
  machine:
    machine:
      image: ubuntu-2004:2023.02.1

jobs:
  build:
    executor: ubuntu_executor
    environment:
      BUILD_CONFIGURATION: Release
      WWWROOT_DIR: Tailspin.SpaceGame.Web/wwwroot
      DOTNET_SDK_VERSION: 6.0
    steps:
      - checkout

      - run:
          name: Install .NET SDK
          command: |
            #wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
            #sudo chmod +x ./dotnet-install.sh
            #./dotnet-install.sh --channel 6.0
            sudo apt-get update
            sudo apt-get install -y apt-transport-https && \
            sudo apt-get update && \
            sudo apt-get install -y dotnet-sdk-6.0
      - restore_cache:
          keys:
            - v1-npm-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Run npm install
          command: npm ci

      - save_cache:
          key: v1-npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Compile Sass assets
          command: ./node_modules/.bin/node-sass $WWWROOT_DIR --output $WWWROOT_DIR

      - run:
          name: Run gulp tasks
          command: npx gulp

      - run:
          name: Write build info
          command: echo "${CIRCLE_PROJECT_REPONAME}, ${CIRCLE_BUILD_NUM}, ${CIRCLE_SHA1}" > $WWWROOT_DIR/buildinfo.txt

      - run:
          name: Restore project dependencies
          command: dotnet restore

      - run:
          name: Build the project
          command: dotnet build --no-restore --configuration $BUILD_CONFIGURATION

      - run:
          name: Publish the project
          command: |
            dotnet publish --no-build --configuration $BUILD_CONFIGURATION --output ./artifacts/$BUILD_CONFIGURATION
            cd ./artifacts/$BUILD_CONFIGURATION
            zip -r ../${BUILD_CONFIGURATION}.zip .

      - store_artifacts:
          path: ./artifacts
          destination: drop

workflows:
  build-deploy:
    jobs:
      - build
